### ISSUE TITLE
ImportError: DLL load failed while importing win32api

### ISSUE THREAD

**Issue by rf13734** [catalystneuro/mease-lab-to-nwb#32]
Hi, please forgive my ignorance on these matters, but it appears there's been a failure to start the kernel. Deepti and I will try and fix it, but thought you guys may want to know.

Traceback (most recent call last):
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_client\manager.py", line 258, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\NeuroNetz\Miniconda3\envs\measelab\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: Das angegebene Modul wurde nicht gefunden.

**Comment by rf13734** [comment]
Fixed it: conda install pywin32

**Comment by luiztauffer** [comment]
@rf13734 good that you managed to solve it! I'll close this issue then
